### ISSUE TITLE
pythonic_testcase dependency not found

### ISSUE THREAD

**Issue by luisza** [FlightDataServices/soapfish#38]
Hi,   I am installing this app from pip but this messages is shown

```
Collecting pythonic_testcase (from soapfish==0.6.0.dev0)
  Could not find a version that satisfies the requirement pythonic_testcase (from soapfish==0.6.0.dev0) (from versions: )
No matching distribution found for pythonic_testcase (from soapfish==0.6.0.dev0)
```
Checking on pypi and google i got than pythonic_testcase was removed from pypi

**Comment by FelixSchwarz** [comment]
Ah sorry, that was my fault. It did not occur to me that soapfish has that as a dependency (even in requirements.txt). Fix incoming.

**Comment by FelixSchwarz** [comment]
fixed in 70bcf4d9102ed7bc34de9ec388894dbadec73b87

Also I thought about removing "PythonicTestcase" from requirements.txt and moving it into "dev_requirements.txt". That would mean users might get an ImportError on "import soapfish.testutil' (and they did not installed the dependencies in "dev_requirements.txt") but that might be a minor issue (if you import a "testutil" package you should have dependencies for development).

Opinions?

A

**Comment by FelixSchwarz** [comment]
Oh, btw: You should not use this repository but https://github.com/soapteam/soapfish . Historically the "soapteam" repo was a fork but it is now "upstream" (see also https://github.com/soapteam/soapfish/issues/110)

**Comment by pope1ni** [comment]
Closing as this has been resolved by Felix.
